# Generated by tools/bake. Do not edit by hand.

group "all" {
  targets = ["nextjs-base", "nextjs-payload", "nextjs-prisma", "nginx-base", "nginx-cdn", "nginx-core"]
}

target "nextjs-base" {
  context = "nextjs/base"
  dockerfile = "Dockerfile"
  platforms = ["linux/amd64", "linux/arm64"]
  tags = ["ghcr.io/gecut/nextjs/base:1.0.0", "ghcr.io/gecut/nextjs/base:latest"]
  args = {
    BUILD_VERSION = "1.0.0"
  }
}

target "nextjs-payload" {
  context = "nextjs/payload"
  dockerfile = "Dockerfile"
  platforms = ["linux/amd64", "linux/arm64"]
  tags = ["ghcr.io/gecut/nextjs/payload:1.0.0", "ghcr.io/gecut/nextjs/payload:latest", "ghcr.io/gecut/nexload:1.0.0", "ghcr.io/gecut/nexload:latest"]
  args = {
    BUILD_VERSION = "1.0.0"
  }
}

target "nextjs-prisma" {
  context = "nextjs/prisma"
  dockerfile = "Dockerfile"
  platforms = ["linux/amd64", "linux/arm64"]
  tags = ["ghcr.io/gecut/nextjs/prisma:1.0.0", "ghcr.io/gecut/nextjs/prisma:latest"]
  args = {
    BUILD_VERSION = "1.0.0"
  }
}

target "nginx-base" {
  context = "nginx/base"
  dockerfile = "Dockerfile"
  platforms = ["linux/amd64", "linux/arm64"]
  tags = ["ghcr.io/gecut/nginx/base:1.0.0", "ghcr.io/gecut/nginx/base:latest"]
  args = {
    BUILD_VERSION = "1.0.0"
  }
}

target "nginx-cdn" {
  context = "nginx/cdn"
  dockerfile = "Dockerfile"
  platforms = ["linux/amd64", "linux/arm64"]
  tags = ["ghcr.io/gecut/nginx/cdn:1.0.0", "ghcr.io/gecut/nginx/cdn:latest"]
  args = {
    BUILD_VERSION = "1.0.0"
  }
}

target "nginx-core" {
  context = "nginx/core"
  dockerfile = "Dockerfile"
  platforms = ["linux/amd64", "linux/arm64"]
  tags = ["ghcr.io/gecut/nginx/core:1.0.0", "ghcr.io/gecut/nginx/core:latest"]
  args = {
    BUILD_VERSION = "1.0.0"
  }
}
