import type { ImageCatalog } from "@gecut/container-catalog";

function quoteList(values: readonly string[]): string {
  return `[${values.map((value) => JSON.stringify(value)).join(", ")}]`;
}

export function generateBakeFile(catalog: ImageCatalog): string {
  const lines: string[] = [
    "# Generated by tools/bake. Do not edit by hand.",
    "",
    `group "all" {`,
    `  targets = ${quoteList(catalog.active_images.map((image) => image.id))}`,
    "}",
    ""
  ];

  for (const image of catalog.active_images) {
    const tags = [
      `${image.canonical_ghcr_path}:${image.current_version}`,
      `${image.canonical_ghcr_path}:latest`,
      ...image.aliases.flatMap((alias) => [`ghcr.io/gecut/${alias}:${image.current_version}`, `ghcr.io/gecut/${alias}:latest`])
    ];
    lines.push(`target "${image.id}" {`);
    lines.push(`  context = ${JSON.stringify(image.source_context)}`);
    lines.push(`  dockerfile = ${JSON.stringify(image.dockerfile.replace(`${image.source_context}/`, ""))}`);
    lines.push(`  platforms = ${quoteList(image.platforms)}`);
    lines.push(`  tags = ${quoteList(tags)}`);
    lines.push("  args = {");
    lines.push(`    BUILD_VERSION = ${JSON.stringify(image.current_version)}`);
    lines.push("  }");
    lines.push("}");
    lines.push("");
  }

  return `${lines.join("\n").trimEnd()}\n`;
}
